export const GEOMETRY_TOKENS = {
  barHeight: 30,
  barHeightThin: 16,
  barHeightThick: 44,
  railWidth: 30,
  railWidthNarrow: 16,
  elbowSize: 120,
  elbowInnerRadius: 34,
  elbowArmHorizontal: 34,
  elbowArmVertical: 34,
  shellRailWidth: 180,
  headerHeight: 74,
  boxSidebarWidth: 150,
  segmentGap: 2,
  frameGap: 0,
  unit: 8,
  buttonMinHeight: 30,
  buttonMinWidth: 100,

  shellElbowSize: 200,
  shellElbowInnerRadius: 52,
  shellElbowArmH: 44,
  shellElbowArmV: 44,

  sweepElbowSize: 180,
  sweepElbowInnerRadius: 48,
  sweepElbowArmH: 40,
  sweepElbowArmV: 40,
} as const;
