export const GEOMETRY_TOKENS = {
  barHeight: 44,
  barHeightThin: 20,
  barHeightThick: 60,
  railWidth: 44,
  railWidthNarrow: 20,
  elbowSize: 120,
  elbowInnerRadius: 50,
  elbowArmHorizontal: 24,
  elbowArmVertical: 24,
  shellRailWidth: 220,
  headerHeight: 110,
  boxSidebarWidth: 150,
  segmentGap: 2,
  frameGap: 0,
  unit: 8,
  buttonMinHeight: 36,
  buttonMinWidth: 110,

  shellElbowSize: 220,
  shellElbowInnerRadius: 72,
  shellElbowArmH: 24,
  shellElbowArmV: 24,

  sweepElbowSize: 180,
  sweepElbowInnerRadius: 66,
  sweepElbowArmH: 22,
  sweepElbowArmV: 22,
} as const;
