import { readFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * `manifestValidator.generated.ts` and `workspaceValidator.generated.ts`
 * (generated by scripts/generate-contract.mjs / generate-workspace-contract.mjs
 * from ajv's `standaloneCode`) are imported directly by App.tsx's module
 * graph, so they are evaluated on every page load — in the browser, not in
 * Node.
 *
 * Ajv's standalone generator hardcodes CJS `require("ajv/dist/runtime/X")`
 * for its internal runtime helpers (ucs2length, equal, uri, ...) no matter
 * what `code.esm` is set to — see node_modules/ajv/dist/runtime/*.js, each
 * of which sets `.code` to a literal require() string. A bundler with CJS
 * interop (Rollup/Rolldown, what `vite build` uses) tolerates that at
 * bundle time, but `vite dev` serves modules through esbuild's per-file ESM
 * transform with no such interop, and a bare vitest/Node run of these files
 * tolerates it too (Node still has a real `require`) — so this exact defect
 * is invisible to `npm run test`, `npm run build`, and a production
 * deployment alike, and only throws `ReferenceError: require is not
 * defined` in an actual browser hitting the dev server. That silence is
 * exactly how it went unnoticed: every E2E test that loads the app crashes
 * before it even renders the boot-status error, so the whole app looks
 * like it "never mounts" rather than like a require() bug.
 *
 * generate-contract.mjs and generate-workspace-contract.mjs now post-process
 * ajv's output through esmifyStandaloneAjvCode (scripts/lib/esmifyStandaloneAjv.mjs)
 * to hoist these into real imports. This test pins that invariant directly
 * against the committed generated files, independent of any bundler or
 * browser — so a future ajv upgrade or a hand-edit that drops the
 * post-processing step fails fast here instead of silently shipping a
 * dev-server (and, if a bundler ever stops shimming it, production) crash.
 */
const generatedValidatorPaths = [
  resolve(process.cwd(), "src/types/manifestValidator.generated.ts"),
  resolve(process.cwd(), "src/types/workspaceValidator.generated.ts"),
];

describe("generated ajv standalone validators are browser-safe ESM", () => {
  test.each(generatedValidatorPaths)("%s contains no CommonJS require()", (path) => {
    const source = readFileSync(path, "utf-8");
    expect(source).not.toMatch(/\brequire\(/);
  });
});
